### ISSUE TITLE
Does not boot

### ISSUE THREAD

**Issue by DunhamGitHub** [agg23/fpga-tamagotchi#4]
### Ask a question

Hi

I got the rom, renamed tama.b to rom.bin (guessing that one since it does not say in the documentation...?)

...what now? All I get is the colorful image on boot, nothing then...

<img width="755" alt="Screenshot 2023-04-29 at 10 03 08" src="https://user-images.githubusercontent.com/6884752/235291945-f1d895c5-a2e7-4679-ae23-211f73dced9a.png">

**Comment by agg23** [comment]
Did you open settings and select `Reset`? That should fix your booting issues.

On another note, what would you like to see improved in the documentation? [Platform Installation](https://github.com/agg23/fpga-tamagotchi/blob/master/docs/platform_installation.md) does call out how to obtain the ROM, and that it's named `rom.bin` on the Analogue Pocket, but I agree that the mix between Pocket and MiSTer is confusing. Any ideas/suggestions are appreciated.

**Comment by DunhamGitHub** [comment]
Reset **worked** (thanks for the tip)

Improvement to the documentation:
a) As mentioned it was unclear that I had to rename _tama.b_ to _rom.bin_
b) This issue. "If you get blank screen, reset Core"

https://user-images.githubusercontent.com/6884752/235332060-c0921814-e0cd-477d-8316-0d81391d6df3.mp4

**Comment by agg23** [comment]
Thanks. I have [added a small snippet to the beginning of the install instructions](https://github.com/agg23/fpga-tamagotchi/blob/master/docs/platform_installation.md#roms). Let me know if you think it needs more details.

I neglected to mention this earlier, but I did add a FAQ section to the bottom of the README that covers the reset case. Would you like to see something in addition to that?

I can't see the video, by the way

**Comment by DunhamGitHub** [comment]
Thanks for that.

Indeed you did cover my initial problem in the FAQ, shame on me for not consulting that.
