### ISSUE TITLE
Link to official manual no longer working

### ISSUE THREAD

**Issue by sl33p** [agg23/fpga-tamagotchi#7]
In the readme this link (https://www.bandai.com/wp-content/uploads/TamaIS_Gen1_pg1.pdf) now leads to a 404. 

It seems the manual has moved to https://www.bandai.com/amfile/file/download/file/167/product/1276811/

**Comment by agg23** [comment]
Thanks for the heads up. I've now provided the manual locally, so it can't disappear on me.
